CREATE TABLE `company`(`ID` int NOT NULL AUTO_INCREMENT, `nam` varchar(500) NULL, `adress` varchar(500) NULL, `mail` varchar(500) NULL, `phon` varchar(500) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `dep`(`ID` int NOT NULL AUTO_INCREMENT, `nm` varchar(50) NULL, `main` varchar(50) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `grouppro`(`ID` int NOT NULL AUTO_INCREMENT, `nam` varchar(50) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `in`(`ID` int NOT NULL AUTO_INCREMENT, `innu` varchar(500) NOT NULL, `group` int NULL, `proid` int NULL, `quit` int NULL, `expireyn` varchar(50) NULL, `expiredate` date NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `inpro`(`ID` int NOT NULL AUTO_INCREMENT, `innm` varchar(11) NOT NULL, `date` date NULL, `comp` varchar(5000) NULL, `note` varchar(500) NULL, `att` varchar(5000) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `lost`(`ID` int NOT NULL AUTO_INCREMENT, `lostnu` varchar(11) NULL, `gro` int NULL, `pro` int NULL, `q` int NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `lostpro`(`ID` int NOT NULL AUTO_INCREMENT, `losnu` varchar(11) NULL, `date` date NULL, `state` int NULL, `note` varchar(50) NULL, `att` varchar(5000) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `maindp`(`ID` int NOT NULL AUTO_INCREMENT, `nam` varchar(50) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `out`(`ID` int NOT NULL AUTO_INCREMENT, `outnu` varchar(11) NULL, `gro` int NULL, `pro` int NULL, `quit` int NOT NULL, `sq` varchar(50) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `outpro`(`ID` int NOT NULL AUTO_INCREMENT, `outnu` varchar(11) NOT NULL, `date` date NULL, `main` int NULL, `dep` int NULL, `note` varchar(50) NULL, `att` varchar(5000) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `pro`(`proid` int NULL, `qin` double NULL, `qot` double NULL, `q` varchar(50) NULL, `too` double NULL)CHARACTER SET utf8;
CREATE TABLE `product`(`ID` int NOT NULL AUTO_INCREMENT, `nu` int NOT NULL, `nm` varchar(50) NOT NULL, `shap` varchar(11) NOT NULL, `group` int NOT NULL, `point` varchar(500) NULL, `note` varchar(50) NULL, `image` varchar(500) NULL, `seri` varchar(50) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `stock_settings`(`ID` int NOT NULL AUTO_INCREMENT, `TYPE` int NULL DEFAULT 1, `NAME` mediumtext NULL, `USERNAME` mediumtext NULL, `COOKIE` varchar(500) NULL, `SEARCH` mediumtext NULL, `TABLENAME` varchar(300) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `stock_users`(`ID` int NOT NULL AUTO_INCREMENT, `username` varchar(255) NULL, `password` varchar(255) NULL, `email` varchar(255) NULL, `fullname` varchar(255) NULL, `groupid` varchar(255) NULL, PRIMARY KEY (`ID`))CHARACTER SET utf8;
CREATE TABLE `inview`(`proid` int NULL, `SUM(quit)` decimal(32,0) NULL)CHARACTER SET utf8;
CREATE TABLE `lostview`(`pro` int NULL, `SUM(q)` decimal(32,0) NULL)CHARACTER SET utf8;
CREATE TABLE `outview`(`pro` int NULL, `SUM(quit)` decimal(32,0) NULL)CHARACTER SET utf8;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `company` (`ID`,`nam`,`adress`,`mail`,`phon`) VALUES (1,'1','','','');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `dep` (`ID`,`nm`,`main`) VALUES (1,'1','1');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `grouppro` (`ID`,`nam`) VALUES (1,'111');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `in` (`ID`,`innu`,`group`,`proid`,`quit`,`expireyn`,`expiredate`) VALUES (13,'3',1,1,100,'',NULL);
INSERT INTO `in` (`ID`,`innu`,`group`,`proid`,`quit`,`expireyn`,`expiredate`) VALUES (17,'3',1,1002,50,'',NULL);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `inpro` (`ID`,`innm`,`date`,`comp`,`note`,`att`) VALUES (10,'3','2023-03-14','1','','');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `inview` (`proid`,`SUM(quit)`) VALUES (1,100);
INSERT INTO `inview` (`proid`,`SUM(quit)`) VALUES (1002,50);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `lost` (`ID`,`lostnu`,`gro`,`pro`,`q`) VALUES (3,'1',1,1,5);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `lostpro` (`ID`,`losnu`,`date`,`state`,`note`,`att`) VALUES (3,'1','2023-03-16',NULL,'','');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `lostview` (`pro`,`SUM(q)`) VALUES (1,5);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `maindp` (`ID`,`nam`) VALUES (1,'1');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `out` (`ID`,`outnu`,`gro`,`pro`,`quit`,`sq`) VALUES (17,'1',1,1,30,'');
INSERT INTO `out` (`ID`,`outnu`,`gro`,`pro`,`quit`,`sq`) VALUES (18,'1',1,1,10,NULL);
INSERT INTO `out` (`ID`,`outnu`,`gro`,`pro`,`quit`,`sq`) VALUES (19,'2',1,1,20,NULL);
INSERT INTO `out` (`ID`,`outnu`,`gro`,`pro`,`quit`,`sq`) VALUES (20,'2',1,1002,30,NULL);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `outpro` (`ID`,`outnu`,`date`,`main`,`dep`,`note`,`att`) VALUES (9,'1','2023-03-16',1,1,'','');
INSERT INTO `outpro` (`ID`,`outnu`,`date`,`main`,`dep`,`note`,`att`) VALUES (10,'2','2023-03-16',1,1,'','');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `outview` (`pro`,`SUM(quit)`) VALUES (1,60);
INSERT INTO `outview` (`pro`,`SUM(quit)`) VALUES (1002,30);
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `product` (`ID`,`nu`,`nm`,`shap`,`group`,`point`,`note`,`image`,`seri`) VALUES (1,1,'صنف1','1',1,'35','','[{"name":"files\\/output-onlinepngtools_7g0zw2f2.png","usrName":"output-onlinepngtools.png","size":2609,"type":"image\\/png","searchStr":"output-onlinepngtools.png,!:sStrEnd"}]','');
INSERT INTO `product` (`ID`,`nu`,`nm`,`shap`,`group`,`point`,`note`,`image`,`seri`) VALUES (2,1002,'صنف 2','2',1,'1','','','');
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
INSERT INTO `stock_users` (`ID`,`username`,`password`,`email`,`fullname`,`groupid`) VALUES (1,'admin','1','','',NULL);
SET FOREIGN_KEY_CHECKS = 1;
